### ISSUE TITLE
RTKNAVI-QT(b34c) Gnd Trk issue

### ISSUE THREAD

**Issue by AlexburkGit** [rtklibexplorer/RTKLIB#100]
![fix_1_rtknavi_qt](https://user-images.githubusercontent.com/64149290/140719611-a952d538-5602-47f9-b92b-85020e93ed0e.png)
[fix_1_rtknavi_qt.txt](https://github.com/rtklibexplorer/RTKLIB/files/7495847/fix_1_rtknavi_qt.txt)

**Comment by rtklibexplorer** [comment]
Thanks for the fix.  Can you submit as part of a pull request and include a comment explaining exactly what this fixes?

**Comment by rtklibexplorer** [comment]
Qt apps no longer supported in the 2.4.3 or demo5 versions of RTKLIB
