### ISSUE TITLE
RTKNAVI-QT(b34c) localdirectory issue (linux)

### ISSUE THREAD

**Issue by AlexburkGit** [rtklibexplorer/RTKLIB#102]
[fix_localdirectory_RTKNAVI-QT.txt](https://github.com/rtklibexplorer/RTKLIB/files/7496085/fix_localdirectory_RTKNAVI-QT.txt)

**Comment by rtklibexplorer** [comment]
Thanks for the fix.  Can you submit as part of a pull request and include a comment explaining exactly what this fixes?

**Comment by rtklibexplorer** [comment]
Qt apps no longer supported in the 2.4.3 or demo5 versions of RTKLIB
