### ISSUE TITLE
RTKNAVI-QT(b34c) SBAS NavData issue

### ISSUE THREAD

**Issue by AlexburkGit** [rtklibexplorer/RTKLIB#104]
![fix_3_rtknavi_qt](https://user-images.githubusercontent.com/64149290/140752185-0e24e627-30ec-4351-9465-7150f0a4a0fb.png)
[fix_3_rtknavi_qt.txt](https://github.com/rtklibexplorer/RTKLIB/files/7497352/fix_3_rtknavi_qt.txt)

**Comment by rtklibexplorer** [comment]
Thanks for the fix.  Can you submit as part of a pull request and include a comment explaining exactly what this fixes?
