### ISSUE TITLE
Demo5 b34c binaries | RTKPOST | ERROR:no position in rinex header

### ISSUE THREAD

**Issue by antoinebio** [rtklibexplorer/RTKLIB#105]
Hi
in Demo5 b34c binaries
I found an issue when working with BASES STATION RINEX
even if the rinex contains geocentric position, it is not well interpretated by RTKPOST

I test the same data set with former releases (demo5_b33 and 2.4.3b34) and the issue is not present.

antoine

**Comment by rtklibexplorer** [comment]
I am closing this issue now.  If you are still seeing this issue with the latest code (b34g or higher), please send me the files and I will take a closer look.
