### ISSUE TITLE
Fix status on console app (rtkrcv)

### ISSUE THREAD

**Issue by athtest800** [rtklibexplorer/RTKLIB#108]
Hi,
When using windows binaries (rtknavi) or when compiling in ubuntu x86 and using rtkrcv, F9P gets FIX status in a minute.
In raspberry pi 4 I cannot get FIX status even if I export the .conf from ubuntu and importing to raspberry rtkrcv for similar configuration.
The test was also taken place simultaneously on ubuntu x86 and raspberry with the same feed but no FIX from raspberry whereas in ubuntu got FIX  in a minute?
Thank you

**Comment by gaofenzi** [comment]
您好，辛苦啦！梦寒已经收到您的珍贵来件，会在最短的时间内给予您最想要的答复！

**Comment by sonicpp** [comment]
I think I was facing the same issue when I was trying it on the raspberry - maybe it is too slow? Or is it because of different architecture? I would try to compile it without the "-g" (debugging symbols), it could speed it up little bit.

**Comment by rtklibexplorer** [comment]
I have tested rtkrcv on multiple Raspberry Pi's without issue.  The faster Raspberry Pis are fast enough to run multiple instances of rtkrcv simultaneously.  I've posted more information on using rtkrcv on the Pi [here](https://rtklibexplorer.wordpress.com/2022/11/10/raspberry-pi-based-ppk-and-rtk-solutions-with-rtklib/).
