### ISSUE TITLE
Comparison with other forks (like Emlid)

### ISSUE THREAD

**Issue by bulvara** [rtklibexplorer/RTKLIB#119]
How does this fork compare to https://github.com/emlid/RTKLIB/tree/reach ?

**Comment by gaofenzi** [comment]
您好，辛苦啦！梦寒已经收到您的珍贵来件，会在最短的时间内给予您最想要的答复！

**Comment by yhzyhzyhz** [comment]
> 

Can you please disable your email autoreply. it replys to everyone.

**Comment by kiufta** [comment]
I would be interested in a clarification, too.

**Comment by Waley04** [comment]
@bulvara, you mean comparison in terms of what?

**Comment by rtklibexplorer** [comment]
That branch has not been updated since 1/20.  It has many of the earlier demo5 improvements ported into it, and also has other features developed by Emlid, some of which have been ported into the demo5 code.
