### ISSUE TITLE
Command in windows to give input to RTLCONV

### ISSUE THREAD

**Issue by ajayavgarde** [rtklibexplorer/RTKLIB#126]
I use ublox to extract the RINEX using the RTKCONV application but want the RTKCONV to run backend using the command line. So can anyone guide how it can be done?

**Comment by rtklibexplorer** [comment]
Use the RTKLIB console app CONVBIN.  Details in the [RTKLIB user manual](https://rtkexplorer.com/pdfs/manual_demo5.pdf).
