### ISSUE TITLE
.YY files

### ISSUE THREAD

**Issue by lucapada** [rtklibexplorer/RTKLIB#128]
What should I type in the shell to get .YYx-files instead of .obs/.nav?
I use `convbin -od -os -ot -oi -ol -c on .\COM80_2022.ubx` but when I press enter I got:
`input file  : .\COM80_2022.ubx (u-blox)
->rinex obs : .\%r%n0.%yO
->rinex nav : .\%r%n0.%yN
->rinex gnav: .\%r%n0.%yG
->rinex hnav: .\%r%n0.%yH
->rinex qnav: .\%r%n0.%yQ
->rinex lnav: .\%r%n0.%yL
->sbas log  : .\%r%n0_%y.sbs
no time for output path: .\%r%n0.%yO`
By using RTKCONV and checking "Scan Obs Types" all goes well...
Thanks in advance!

**Comment by rtklibexplorer** [comment]
From [RTKLIB user manual](https://rtkexplorer.com/pdfs/manual_demo5.pdf), appendix A.4
-o ofile output RINEX OBS file
 -n nfile output RINEX NAV file
 -g gfile output RINEX GNAV file
 -h hfile output RINEX HNAV file
 -q qfile output RINEX QNAV file
 -l lfile output RINEX LNAV file
 -b cfile output RINEX CNAV file",
 -i ifile output RINEX INAV file",
 -s sfile output SBAS message file
