### ISSUE TITLE
Compilation error in rcvraw.c

### ISSUE THREAD

**Issue by anestorov** [rtklibexplorer/RTKLIB#13]
Hello I just get a compilation error I am pasting below. I just comment input_tersus function ...

rcvraw.o: In function `input_raw':
/home/admin/RTK/RTKLIB/app/rtkrcv/gcc/../../../src/rcvraw.c:1002: undefined reference to `input_tersus'
rcvraw.o: In function `input_rawf':
/home/admin/RTK/RTKLIB/app/rtkrcv/gcc/../../../src/rcvraw.c:1032: undefined reference to `input_tersusf'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'rtkrcv' failed
make: *** [rtkrcv] Error 1

**Comment by rtklibexplorer** [comment]
Hi Anestorov,

The b28 changes from the official release included support for the Tersus
receiver and added a new source file tersus.c.  They forgot to add
references to the new file in the makefiles for several of the
applications.  I fixed most of these but looks like I missed RTKRCV.  I'll
fix this in my next checkin.

In the meantime you can fix this yourself by adding tersus.c and tersus.o
to the makefile file in the /app/rtkrcv/gcc folder.  Just copy the format
from one of the other files.

Thanks for making me aware of the issue.

Tim
