### ISSUE TITLE
FFRT Ratio Test

### ISSUE THREAD

**Issue by ellafredeluces** [rtklibexplorer/RTKLIB#131]
Hello, 

I would like to ask how did you calculate for the critical/threshold value for ratio test as you described here in your blog? 
https://rtklibexplorer.wordpress.com/2021/07/22/a-variable-ambiguity-resolution-threshold-for-rtklib/ 

Also, where can I see it in the source code of demo5 b34c? 
Thank you very much.

**Comment by rtklibexplorer** [comment]
I used a polynomial fit to adjust the AR threshold value based on the number of satellites.  I used polynomial coefficients that generated a curve that closely matches the FFRT adjustments as shown in the plot in my blog post.  The code to do this is in resamb_LAMBDA() function in rtkpos.c.  Look for the comment "adjust AR ratio based on # of sats".
