### ISSUE TITLE
BeiDou Support for RINEX v2.12

### ISSUE THREAD

**Issue by Dan-Martin512** [rtklibexplorer/RTKLIB#133]
when using convbin.exe with the flag "-v 2.12" i get a BeiDou cnav file but it is empty. In the code it looks like the support for it and the file being generated is covered by an if statement on the version number but then the data is not populated because of another if version clause.
I wonder if there is a reason BeiDou has been kept out for that?

**Comment by rtklibexplorer** [comment]
I don't believe there was ever an official 2.12 RINEX version but the 2.11 version did not support Beidou and according to the RTKLIB release notes [here](https://www.rtklib.com/rtklib_2.4.0_releasenote.htm), the 2.12 version does not either.
