### ISSUE TITLE
Qt version to build the GUI apps

### ISSUE THREAD

**Issue by Nanich87** [rtklibexplorer/RTKLIB#144]
I am trying to build the GUI apps but the script terminates while trying to build rtkget_qt with this error:
```
getmain.cpp:507:35: error: ‘class QDropEvent’ has no member named ‘position’; did you mean ‘posted’?
     if (StaList == childAt(event->position().toPoint()))
```

```
qmake --version
QMake version 3.1
Using Qt version 5.9.5 in /usr/lib/x86_64-linux-gnu
```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

**Comment by nicholasdalhaug** [comment]
It is worth noting [this comment](https://github.com/rtklibexplorer/RTKLIB/pull/138#issuecomment-1479990980) that says that the Linux GUI is not maintained, but it is available for resurrection if someone wants to do it.
