### ISSUE TITLE
Feature Request -- L5

### ISSUE THREAD

**Issue by SBFRF** [rtklibexplorer/RTKLIB#147]
The documentation states this is a single/dual band package.  Is there any plans to incorporate the third L5 for GPS (or others for other GNSS constellations)?

**Comment by rtklibexplorer** [comment]
The demo5 RTKLIB code does support three frequencies for the GPS, GLONASS, Galileo, and Beidou constellations.  The latest release (b34h) has some improvements specifically for triple frequency solutions, especially Beidou.  I have updated the readme file to indicate that triple frequency solutions are supported.

**Comment by SBFRF** [comment]
copy that, thank you!
