### ISSUE TITLE
RTKCONV does not time corr .ubx file if Time Start - Time End options are selected

### ISSUE THREAD

**Issue by John-2222** [rtklibexplorer/RTKLIB#158]
Problem found when converting 1 Hz raw observation ubx file to obs file, where time has small difference from integer seconds.  
For full file, it corrects the time to integer seconds; even if Time Corr box is not checked.  That's fine.
If the Time Start and Time End options are checked, the adjustment to integer seconds does not happen.

**Comment by rtklibexplorer** [comment]
These sound like two different issues.  If you send me an email at rtklibexplorer@gmail.com with the file in question and the exact command lines used I will take a look.

**Comment by rtklibexplorer** [comment]
Fixed with commit on 12/8/23
