### ISSUE TITLE
Hi, how to post-processing if I just have Ublox M8T rover RAW data with .ubx

### ISSUE THREAD

**Issue by roger-zhao** [rtklibexplorer/RTKLIB#16]
Could I just put this data into RTKNAVI (rover input(input type-file: ***.ubx, base input(input type ntrip CORS), then log the base data as RTCM3, and then using these two files in RTKPOST? But if so, how can I deal with timetag for  larger Age diff?

**Comment by rinex20** [comment]
rtkpost for post-processing.

**Comment by rtklibexplorer** [comment]
Timetags are only necessary when emulating a real-time solution with files, they are not used in post-processing since when the data became available is not relevant.
