### ISSUE TITLE
rtkplot_qt does not show plot

### ISSUE THREAD

**Issue by brandy125** [rtklibexplorer/RTKLIB#160]
After compiling successfully on my Suse Tumbleweed aarch64 I start rtkplot_qt and get the following message right after starting the program:

```
QObject::connect: No such slot Plot::MenuShapeFileClick() in plotmain.cpp:308
QObject::connect:  (sender name:   'MenuShapeFile')
QObject::connect:  (receiver name: 'Plot')
```

After opening an .obs file I can not see the plot.

Any guess?

**Comment by rtklibexplorer** [comment]
The "dev" branch of this repo now contains support for the QT GUI apps and should work for you.  These changes will be pulled into the main branch at some point in the future.

**Comment by brandy125** [comment]
Thanks!
