### ISSUE TITLE
rnx2rtkp.exe satellite system selection issues using MIXED Rinex NAV-files

### ISSUE THREAD

**Issue by Isulv** [rtklibexplorer/RTKLIB#162]
It's not possible to disable satellite systems  using MIXED Rinex  NAV-Files in rnx2rtkp.exe. All available satellite systems are always included in the processing.

From command line (trying to select GPS and Galileo): 
-sys G,E  //does not work

In configuration file:
-k  myGPSGAL.conf
pos1-navsys        =9        # (1:gps+2:sbas+4:glo+8:gal+16:qzs+32:bds+64:navic)   //does not work

**Comment by rtklibexplorer** [comment]
I confirmed the bug in the command line option and have just pushed a fix for it to the repo.  It will be part of the next code release.  

I am not able to duplicate the problem you are having when changing the config file.  Is it possible you are changing a different version of the config file than the one you specified on the command line?
