### ISSUE TITLE
[bcc32 Fehler] naviopt.cpp(419): E2451 Undefined Symbol 'MaxPosVarAR'

### ISSUE THREAD

**Issue by naseweiss01** [rtklibexplorer/RTKLIB#24]
Hello,
when compiling the latest version , I get this error 5 times. Version from 2 days before compiles with no error.

Best regards 

Urs

**Comment by rtklibexplorer** [comment]
Sorry about that ... my mistake.  Should be OK now.

Tim

**Comment by naseweiss01** [comment]
thanks, that is what I call service.
But I will try only tomorrow - time to see the bed. :-)

Urs

**Comment by naseweiss01** [comment]
Perfect,
works great.

Urs
