### ISSUE TITLE
RTKLIB #FRQ 5 4 3 2 1 in RTKPLOT

### ISSUE THREAD

**Issue by FelipeCarvajalRodriguez** [rtklibexplorer/RTKLIB#254]
Hi all, 

I am looking for the meaning of #FRQ 5 4 3 2 1 in this version of RTKLIB. In previous versions, the green color represented L1/2, but now I cannot find this information. 

Thanks in advance

![2024-04-26_17-01-49](https://github.com/rtklibexplorer/RTKLIB/assets/50501964/d40b4ac1-fdec-4407-9d99-aa36df1b2573)

**Comment by t2rtech** [comment]
The red color indicates that at a certain moment of the collection, there are 3 frequencies for each satellite. Where the red overlaps the green (L1/L2), and the green overlaps the orange (only L1).

In the case you showed in the image, the satellite G23 started collecting L1/L2, and after a period, it began receiving one more frequency (L5?).
