### ISSUE TITLE
Found an Issue in convrnx

### ISSUE THREAD

**Issue by sean10776** [rtklibexplorer/RTKLIB#256]
When converting RTCM data in `convbin`, or `rtkconv` the modification time of the file is used as the start time. However, if `-te` is set and its value is less than the modification time of the file, it results in the conversion being skipped.

For example, if my file records observations on April 29, 2024, but the file modification time is April 30, setting `-te` to specify the observation period leads to the conversion not initiating.

My solution is to adding the following segment to `convrnx.c`:
```c
//convrnx.c
if (format==STRFMT_RTCM2||format==STRFMT_RTCM3||format==STRFMT_RT17) {
    str->time=opt->trtcm;
}
else if (opt->ts.time) {
    str->time=timeadd(opt->ts,-1.0);
}
//Add the following segment
if (opt->te.time && timediff(opt->te,str->time) < 0.0) { 
    str->time=timeadd(opt->te,-1.0);
}
```

**Comment by rtklibexplorer** [comment]
The RTCM3 format contains only relative date information to reduce bandwidth, so RTKLIB needs to know the approximate data start time to reconstruct the exact start time.  In RTKCONV, this can be specified with the -tr option.  In RTKCONV, the GUI will ask for the approximate start time when converting RTCM data.  I believe that in your case, specifying the approximate start time with the -tr option will resolve the problem.  If that is not the case, please add a comment and I will reopen this.
