### ISSUE TITLE
str2str and strsrv

### ISSUE THREAD

**Issue by zuliani71** [rtklibexplorer/RTKLIB#34]
Hello,
I'm using both str2str and strsvr to redirect a stream coming from a serial port to a TCP socket. 

First test: strsvr
The first test is made on my Windows PC (which runs the rtklib GUI), the PC serial port is plugged to a GNSS receiver which yelds RTCM3 messages. The app strsrv works great, I can grab its redirected TCP stream with rtknavi and I'm able to see the RTCM3 messages in the (1) Rover panel (available from the popup menù of rtknavi).
The config is the following:
(0) Input, Serial, Port COM4, Bitrate 115200, Byte size 8, Parity None, Stop bits 1, Flw Ctrl none
(1) Output, TCP Server, Port 3333 
rtknavi is configured to capture the RTCM3 stream from the local server 127.0.0.1:3333

I've tried to do the same with str2str from a linux box. For this second attempt the same receiver is plugged to the serial port of a Linux machine.
The command I use is the following:
str2str -in serial://ttyUSB0:115200:8:o:1:off -out tcpsvr://:3333
I use again rtknavi on my Windows PC to grab the stream from the 3333 port of the linux TCP server (which is now the Linux box IP address). I can see the data flow because of the green light in the upper right corner of rtknavi (an even inside the info panel for the streams). Unfortunately form the (1) Rover panel of rtknavi I can see the stream if I choose HEX or ASCII visualization but nothing is showed if I select RTCM3 (or RTCM2).

Both Windows and Linux box are under the same TCP/IP subnet.
Is this caused by a bug inside str2str?

**Comment by olofcarlsson** [comment]
Hello, have you got this working yet? I think you have to specify which type of stream that you want to be available on the tcp-port. Try to change your input string to: tcpsvr://:3333#rtcm3 and then you can specify which RTCM3-messages you want to transfer.  You can look at this example string:
str2str -in serial://ttyUSB0:115200:8:n:1:off#ubx -out tcpsvr://:3333#rtcm3 -c your_cmd_file.cmd -msg 1002,1006,1010,1019,1020,1045,1046
