### ISSUE TITLE
New version dont convert RTCM 1074

### ISSUE THREAD

**Issue by messplay** [rtklibexplorer/RTKLIB#351]
Hi friends, new version dont convert 1074 to rinex can you verify please
[data14.zip](https://github.com/user-attachments/files/15686841/data14.zip)

**Comment by rtklibexplorer** [comment]
Are you able to convert the 1074 messages in this file with any other tool?  Neither the previous demo5 release (b34i) or the 2.4.3 b34 release are able to do it either.  By enabling the trace debug, I see parity errors on the 1074 messages.  This does not appear to be a problem with the new release and I suspect it is a problem with the data file.

**Comment by messplay** [comment]
Hi Friend I will check Thank you for you support and great job
