### ISSUE TITLE
Ublox ZED-F9P bad measurements time

### ISSUE THREAD

**Issue by vmotorkin** [rtklibexplorer/RTKLIB#39]
Need a ubx_f9p_1hz.cmd , because correct measurements should be multiple of one second. Now, measurement show 1 m/second shift.
example:
07.02.2019 14:09:58.000
07.02.2019 14:09:59.000
07.02.2019 14:09:59.999
07.02.2019 14:10:00.999
07.02.2019 14:10:01.999
...
07.02.2019 14:33:30.999
07.02.2019 14:33:32.000

---

**Comment by rtklibexplorer** [comment]
The u-blox raw observation time stamps include an estimate of local clock error so will not align exactly with the specified interval.  This is not something that can be changed with the *.cmd file.
