### ISSUE TITLE
rtkplot_qt observation type codes not handled well

### ISSUE THREAD

**Issue by ourairquality** [rtklibexplorer/RTKLIB#392]
In the Qt plot interface cBObservationType is given integer values for the frequencies and strings such as '2I' for the codes. The code reading back the selected option uses `if (obstype.canConvert<int>())` to check if it is a frequency vs a code but this fails because this method returns true even for these codes, and then  obstype.toInt() returns zero, and then 0 - 1 is used as an array index leading an OOB access.

**Comment by JensReimann** [comment]
Thank you for reporting the issue. It is not obvious that QString can be converted to int!

The latest version should address the problem and uses a different technique to distinguish between the types stored in obstype.

**Comment by ourairquality** [comment]
Thank you.
