### ISSUE TITLE
rtkpost_qt demo5 b34j does not generate a solution for several base station files if ? wildcard character is specified

### ISSUE THREAD

**Issue by szymon2024** [rtklibexplorer/RTKLIB#394]
-

**Comment by JensReimann** [comment]
Does the problem also occur with the console or windows apps? I guess it is a fundamental problem of rtklib and not only related to rtkpost_qt.

**Comment by JensReimann** [comment]
Reading the documentation section 3.4 and looking into expath() it looks like only * is supported by rtklib. I wonder why the ? wildcard works for you.

Maybe it is handled by crx2rnx or the shell while executing crx2rnx? Can you check whether the ? wildcard works with the windows apps on uncompressed rinex files?

**Comment by rtklibexplorer** [comment]
The Windows functions called by expath (FindFirstFile and FindNextFile) support both '*' and '?' wildcards.  The '?' can be a useful feature when dealing with many input files but as mentioned above, this is not a documented feature of RTKLIB.

I would suggest changing this issue from a bug report to a feature request, either by retitling it or closing it and opening a new issue.
