### ISSUE TITLE
rtkpost_qt  demo5 b34j "sh: crx2rnx: not found" message

### ISSUE THREAD

**Issue by szymon2024** [rtklibexplorer/RTKLIB#395]
-

**Comment by rtklibexplorer** [comment]
For windows, crx2rnx.exe is included as part of the release code but does need to be in the same folder as the executables.  For linux, I believe you will need to compile this file.

**Comment by JensReimann** [comment]
For the moment, I added a message box to inform the user about potentially missing tools like crx2rnx when decompression fails and point the user to a website where they can download crx2rnx (the most likely missing tool).
