### ISSUE TITLE
rtkpost_qt demo5 b34j decimalPoint problem for base station coordinates

### ISSUE THREAD

**Issue by qgis2000** [rtklibexplorer/RTKLIB#396]
I have an operating system where decimal point is a comma. All numbers in Options... are displayed with a comma. When I enter the Base Station X/Y/Z-ECEF m coordinates with a comma, no calculations are performed. Calculations are performed when I enter these coordinates with a dot as decimal point.

**Comment by JensReimann** [comment]
The input for the base station position has an own-written logic for validating the input. It is not localization aware (like decimal separator). I hope I can fix it in the next release.

**Comment by JensReimann** [comment]
Can you please test the latest version?
