### ISSUE TITLE
rtkpost_qt demo5 b34j  Base Station X/Y/Z-ECEF are not converted to Lat/Lon/Heigth (deg/m)

### ISSUE THREAD

**Issue by qgis2000** [rtklibexplorer/RTKLIB#397]
In Options..., Positions tab, I have the base station coordinates in the X/Y/Z-ECEF format. When I change the format to Lat/Lon/Heigth (deg/m) then Lat=-90.000000000 ° and Lon=0.000000000 °

**Comment by JensReimann** [comment]
This is related to #396

**Comment by JensReimann** [comment]
I made the input validation respect the system localisation. Please test if this fixes the problem for you.

**Comment by JensReimann** [comment]
The Qt GUI is specially designed to be easy for users. This includes localization.

The latest update does not use self-written regular expressions anymore, but use standard validations. Additionally, invalid inputs are highlighted and the format cannot be changed anymore if the input is not valid. This should prevent users from losing their inputs.
