### ISSUE TITLE
rtkpost_qt demo5 b34j cannot enter a comma in the lon field of the base station

### ISSUE THREAD

**Issue by qgis2000** [rtklibexplorer/RTKLIB#398]
I have comma as decimal point. I can not enter comma in the Lon field of base station when Lat/Lon/Height (deg/m) format is set. I can enter comma for Lat and Height only.

**Comment by JensReimann** [comment]
Unfortunately, I cannot reproduce the problem. I can enter a comma even in the Lon field. 

The input is check while typing. So if you try to remove the point as decimal separator, the resulting values still have to be in a valid range or you are not allowed to remove the character. 
This is not yet a perfect solution.
