### ISSUE TITLE
app\strsvr_qt\svrmain.cpp

### ISSUE THREAD

**Issue by IvanKor** [rtklibexplorer/RTKLIB#4]
D:\Qt\Qt5.4.2\Examples\Qt-5.4\RTKLIB-demo5\app\strsvr_qt\svrmain.cpp:599: ошибка: C2660: 'strsvrstart' : function does not take 7 arguments

**Comment by rtklibexplorer** [comment]
The Qt apps are no longer supported in the 2.4.3 or demo5 RTKLIB.
