### ISSUE TITLE
undeclared FREQ1 and FREQ2 in app/rtkplot_qt/plotdraw.cpp

### ISSUE THREAD

**Issue by chungying** [rtklibexplorer/RTKLIB#40]
At lines [971](https://github.com/rtklibexplorer/RTKLIB/blob/16ea34b3b52d0cee97d27c71a6174af8f48f00a5/app/rtkplot_qt/plotdraw.cpp#L971) and [1158](https://github.com/rtklibexplorer/RTKLIB/blob/16ea34b3b52d0cee97d27c71a6174af8f48f00a5/app/rtkplot_qt/plotdraw.cpp#L1158), FREQ1 and FREQ2 should be updated to FREQL1 and FREQL2.

**Comment by rtklibexplorer** [comment]
Fixed
