### ISSUE TITLE
rtkplot_qt demo5 b34j Time Span/Interval... window is always displayed in the upper left corner of the screen

### ISSUE THREAD

**Issue by szymon2024** [rtklibexplorer/RTKLIB#401]
-

**Comment by JensReimann** [comment]
You give more details on this issue? 
Do I understand correctly, that the dialog window is placed in the very top left corner so that the title bar of the window is outside the screen?

**Comment by JensReimann** [comment]
There is no explicit positioning of the windows for neither of the applications. Maybe your desktop environment remembers the last position and always restore it. Which desktop environment are you using on Linux? Have you tried to hold down "Alt gr" key to grab and move the window even when the title bar is not accessible?
