### ISSUE TITLE
rtkplot_qt demo5 b34j Default value of start time of Time Span/Interval... window is different from the chart

### ISSUE THREAD

**Issue by qgis2000** [rtklibexplorer/RTKLIB#402]
The Time Span/Interval... window shows the start time shifted in relation to the Plot Type=Position chart.

**Comment by JensReimann** [comment]
Will be fixed with the next update.

**Comment by JensReimann** [comment]
Please test the latest git version. Hopefully you can confirm the time is now correctly shown.

**Comment by JensReimann** [comment]
Which Qt version do you use? Qt5?
I changed to code to include <QTimeZone> which should fix  compilation. Please try.

**Comment by JensReimann** [comment]
Yes, you are right. I have tested it only against Qt6, but for Qt5 you have to use utc(). 
It should now compile with Qt5, too.

BTW: there are also some fixes for the other issues reported by you committed.
