### ISSUE TITLE
rtkconv_qt demo5 b34j "QMetaObject::invokeMethod: No such method MainWindow::showMessage(QString)"

### ISSUE THREAD

**Issue by qgis2000** [rtklibexplorer/RTKLIB#403]
After clicking the Convert button in the terminal window the following message is displayed repeatedly:
QMetaObject::invokeMethod: No such method MainWindow::showMessage(QString)

**Comment by JensReimann** [comment]
Does this problem show also in the very latest version? It should already be fixed with the "Rtkconv_qt updates" commit of June 12th.
