### ISSUE TITLE
rtkconv_qt demo5 b34j Unable to uncheck the path with the sbs file

### ISSUE THREAD

**Issue by qgis2000** [rtklibexplorer/RTKLIB#404]
Cannot deselect path with sbs file in RINEX OBS/NAV/GNAV/HNAV/QNAV/LNAV and SBS
even though in Options... in Satellite Systems, SBS is unchecked.

**Comment by JensReimann** [comment]
Thanks for reporting. This problem also applies to the other input check boxes. 

I fixed the problem in my local branch already.

**Comment by JensReimann** [comment]
Please test the latest release which should fix the issue
