### ISSUE TITLE
L1 to FRQ4 and and L2 to FRQ5 assignment in rtkplot_qt

### ISSUE THREAD

**Issue by qgis2000** [rtklibexplorer/RTKLIB#429]
For example, when I press "Call rtkplot on (rover) observations" button in rtkpost_qt L2 is FRQ=5 and L1 is FRQ=4.

By the way FRQ=1 in rtkpost_qt is red and in rtpost.exe is orange.

**Comment by JensReimann** [comment]
Can you please give more details?
I guess you're talking about the "Sat Vis" plot of rtkplot_qt, the default when opening rtkplot_qt from rtkpost_qt. 
How do you identify that L2 is FRQ=5 and L1 is FRQ=4?

Normally, the color/legend indicates the _number_ of available codes (not necessarily frequencies).

**Comment by JensReimann** [comment]
The colors can be changed in the options dialog. I will do an update soon to better match the default colors to the once from rtkplot.exe

**Comment by JensReimann** [comment]
I will change the label to #OBS to make the meaning clearer.
