### ISSUE TITLE
Keyword Replacement in File Path for RINEX OBS: Base Station does not work in rtkpost.exe and rtkpost_qt

### ISSUE THREAD

**Issue by szymon2024** [rtklibexplorer/RTKLIB#430]
-

**Comment by JensReimann** [comment]
Hi qgis2000,
please checkout the latest update. The check whether an input file exists was too strict. I fixed this.

**Comment by JensReimann** [comment]
If the decompression tools are missing, please install crx2rnx as indicated by the dialog box. The tools are not distributed with the rtklib source repository.

The keyword %n, %h, %M are only supported if a timespan is selected, see manual chapter 3.5, table for "Station ID List". Did you specified a processing time span?
