### ISSUE TITLE
Unclear message when nav file is missing in rtkpost_qt

### ISSUE THREAD

**Issue by qgis2000** [rtklibexplorer/RTKLIB#431]
If I don't specify NAV file and press "Execute" I get "File not found" window with message:
The specified input file "path/namename" was not found.
The name is typed twice and without extension.

**Comment by JensReimann** [comment]
Dear qgis2000, 
thank you for reporting the issue. The code to derive the nav filename from the observation was wrong. Please test again.

**Comment by JensReimann** [comment]
Sorry. Added the missing files.
