### ISSUE TITLE
rtknavi_qt: ini file boolean settings are not read back correctly so some of the saved state is lost

### ISSUE THREAD

**Issue by ourairquality** [rtklibexplorer/RTKLIB#433]
Boolean values in the settings ini file, with values "true" or "false", are not read back correctly by the typical code `settings.value("prcopt/...", 0).toInt()`.

Perhaps these settings could be written to the ini file as integers, or alternatively some helper function might be needed when loading these settings.

**Comment by JensReimann** [comment]
Thanks for pointing to this issue. To stay compatible to the winapp, the boolean values are stored as integers which fixes the bug.
