### ISSUE TITLE
RTKNavi b31a binary chrashes when configured for SSR PPP L1/L2/E5 

### ISSUE THREAD

**Issue by joebre** [rtklibexplorer/RTKLIB#44]
RTKExplorer RTKnavi binary (b31a ) crashes (on aWindows7 x64 host) if configured to work with the following configuration:
- UBX ZED-F9P
- PPP static (or dynamic)
- Correction source SSR CLK93
- Constellation don't care

RTKnavi works well in the other positioning mode (welcome GALILEO E5)

**Comment by rtklibexplorer** [comment]
I'm not sure if you are having this problem with code you built or after downloading my exectuables.  I had the exact same problem last week and found it was a build issue that occurred after migrating to the newest edition of the Embarcadero compiler and not doing a full re-build of the code. I uploaded a rebuilt executable for RTKNAVI on 7/23/19 so I believe my executables are OK now.
