### ISSUE TITLE
Not enough double-differenced residual

### ISSUE THREAD

**Issue by patrikpordi** [rtklibexplorer/RTKLIB#440]
Hey!

I am trying to make RTKLIB work, however I get not enough double-differenced residual error constatnly whatever I do.
My rover is Teseo-LIV4F that sends RTCM 3 messages and my base station is a Ublox ZED-F9P that also sends RTCM, I tried to play with the navigation systems and went to different locations with clear sky, but no luck. When I started with RTKLIB it worked for a while, but even with fixed the location was jumping around by 50 meters, I wanted to investigate that and then it stopped working at all.
Does anybody have any ideas what to do?
![Screenshot from 2024-08-08 15-24-55](https://github.com/user-attachments/assets/9a57b3f2-86c7-414c-bbeb-75d2a3f7015d)

**Comment by rtklibexplorer** [comment]
I am going to close this as I don't believe it is a code issue.  Based on the extremely large residuals in your screen shot, I suspect your base position may be configured incorrectly.
