### ISSUE TITLE
using convbin.exe to convert rtcm3 into rinex, the GLO is missing L1,L2 data

### ISSUE THREAD

**Issue by fuyongjia** [rtklibexplorer/RTKLIB#476]
![image](https://github.com/user-attachments/assets/95cd4529-bf99-4f21-87e9-1f31a548fd16)
The RTCM data includes broadcast ephemeris.

**Comment by ourairquality** [comment]
Do not see this, in demo5. Perhaps run convbin with tracing enabled and check on the messages being received, its it 1012 or the MSM messages, just to be sure that the data is in the stream, and it might narrow it down.

**Comment by fuyongjia** [comment]
When I use rtkconv.exe, I manually configured the FCN table, and the converted rinex result file is complete.
![image](https://github.com/user-attachments/assets/bd371222-0fdd-4d83-b26d-9c2a75650c8a)
![image](https://github.com/user-attachments/assets/aec869e7-5e88-4c3e-aafa-d31173ebd499)

**Comment by ourairquality** [comment]
Yes it needs the frequency to be able to produce the carrier phase. This appears to be included in the MSM5 and MSM7 messages, or be obtained from the nav data, or as you noted can be prefilled in the nav.glo_fcn from the glofcn option but this option is not available on the command line app convbin and perhaps that support needs to be added.

**Comment by ourairquality** [comment]
The was reproducible using RTCM3 MSM6 which lacks the GLONASS fcn, and initializing the fcn overcame this.

https://github.com/rtklibexplorer/RTKLIB/pull/485 adds support to the convbin command line tool, e.g.

`convbin --glofcn "1,-4,5,6,1,-4,5,6,-2,-7,0,-1,-2,-7,0,-1,4,-3,3,2,4,-3,3,2" ...`
