### ISSUE TITLE
RTKPOST: not works Keyword replacement

### ISSUE THREAD

**Issue by freeExec** [rtklibexplorer/RTKLIB#5]
I use templates such as type ```..\..\RINEX\%Y\%W\%D\igr%W%D.sp3``` for precise ephemeris and they do not work, the keys are not replaced.

**Comment by rtklibexplorer** [comment]
The keyword replacements are intended for specifying output filenames using the current time and date.  To use wildcards in the input files such as the precise ephemeris file, '*' and '?' can be used as wildcards.
