### ISSUE TITLE
GUI isn't scaled properly in RTKPOST on 4K display

### ISSUE THREAD

**Issue by alehanderoo** [rtklibexplorer/RTKLIB#50]
The window of RTKPOST can't be scaled in vertical dimension.
Sometimes the scaling is set to a size where the process, options etc. buttons can't be accessed.
![Capture RTKPOST](https://user-images.githubusercontent.com/28675787/73084073-94dd4100-3ecc-11ea-9b1a-cd9530b03a9d.PNG)

**Comment by rtklibexplorer** [comment]
This appears to be the same issue as #48 and #49 for which there is a solution described in issue #48 
Let me know if that is not the case and this is a different issue in which case I will reopen it.
