### ISSUE TITLE
rtkrcv crashing when reconnecting with telnet - race condition between vt_close() and con_close()

### ISSUE THREAD

**Issue by RobinDumeige** [rtklibexplorer/RTKLIB#54]
To reproduce, on latest debian :
launch rtkrcv with telnet on
`./rtkrcv -p 12345`
then connect to the console with telnet
`telnet localhost 12345`
type the password (default one is admin)
then just type :
`exit`.
When you try to reconnect with
`telnet localhost 12345`
rtkrcv crashes with this message : 
`malloc(): unsorted double linked list corrupted`
`Aborted`

This is due to vt_close() being called inside the spawned console thread (con_thread()). It's freeing the vt struct and this sometime happens before con_close() is called. Since con_close() is writing on vt->status (to handle other types of console closings I guess) it breaks malloc's internals, which crashes the program when next malloc() occurs.

The best way I've found to resolve this issue it so move the call to vt_close() from con_thread() to con_close(). By placing it right after thread.join(), we insure that the console thread is closed and we won't have any further access to the vt struct.

I had the same error message when quitting a non-telnet rtkrcv using shutdown. this fix resolved it too.

**Comment by rtklibexplorer** [comment]
Fixed in 4/17/23 commit
