### ISSUE TITLE
Missing ss2.c and #define

### ISSUE THREAD

**Issue by pvazteixeira** [rtklibexplorer/RTKLIB#65]
I ran into the following issues when building this fork of rtklib (17a7219) in linux:

- `ss2.c` was not found 

- missing `#define`s in `src/rtklib.h` for `FREQTYPE_L6` through `FREQTYPE_L9`, required by `app/rtkconv/codeopt.cpp`

I copied the missing file over from the original RTKLIB (ran into #32 ), added placeholder values for the missing constants and the build finished successfully.

**Comment by rtklibexplorer** [comment]
Fixed in the most recent code.
