### ISSUE TITLE
New Commit Breaks RTKRCV - 6f40c413e69312bdf032a1827f3eaad7ac068d9b

### ISSUE THREAD

**Issue by ban1080** [rtklibexplorer/RTKLIB#69]
Hi, 

When building rtkrcv:

"../../../src/rcv/swiftnav.c:298:12: error: static declaration of ‘uraindex’ follows non-static declaration
 static int uraindex(double value) {"

"makefile:71: recipe for target 'swiftnav.o' failed
make: *** [swiftnav.o] Error 1
make: *** Waiting for unfinished jobs...."

**Comment by rtklibexplorer** [comment]
Thanks for catching this.  Fixed with 11/1/20 commit
