### ISSUE TITLE
build issues on Embarcadero C++Builder 10.3

### ISSUE THREAD

**Issue by vbnhu** [rtklibexplorer/RTKLIB#72]
I tried to build from source the following projects with Embarcadero C++Builder 10.3 (b33d):
app\rnx2rtkp\bcc_win64\_rnx2rtkp_win64.cbproj --> success
app\rtkpost_win64\rtkpost_win64.cbproj --> success

app\convbin\bcc\_convbin.cbproj --> failure , original setting is Win32, after Error I added the target platform Win64 and now it is a success
app\rtkconv\rtkconv.cbproj --> failure , I changed it to Win64 platform but I still receive an error: "[bcc64 Error] rtkconv.cpp(32): C++ requires a type specifier for all declarations"

Anyone having the same problems?

**Comment by rtklibexplorer** [comment]
Thanks for flagging this. It should be fixed with my 11/27/20 commit
