### ISSUE TITLE
skyplot and -TADJ option

### ISSUE THREAD

**Issue by zuliani71** [rtklibexplorer/RTKLIB#76]
I've recently tried the -TADJ = 1 option to adjust the time stamps to round values (in seconds) when converting from raw ubx files to RINEX 2.11 files.

I've successfully used this option both in convbin and rtkconv (coming from RTKLIB 2.4.3 b33e demo59. The final RINEX files include only integer time stamps. Unfortunately the price to pay is a heavy scattered skyplot, and this is probably an evidence of wrong nav files.

Here below a couple of skyplots coming from two tests. They've been produced with rtkconv, starting from the same raw file and using the same conversion parameters except one. The first one is produced without the -TADJ=1 option, the second one with the -TADJ=1 enabled.
 
![output notadj](https://user-images.githubusercontent.com/2155581/103484446-36fced00-4def-11eb-8da6-1c1c2ba7bafb.jpg)

![output tadj](https://user-images.githubusercontent.com/2155581/103484517-aecb1780-4def-11eb-9228-eec9b637adcb.jpg)

As you can see the second plot is more scattered. Probably also the nav files need to be fix for the -TADJ=1 (not only the RINEX observables) but probably they are not. Is there a way to adjust this behavior?

**Comment by rtklibexplorer** [comment]
This was a bug.  Fixed in the b34a version
