### ISSUE TITLE
prange() tests P1==0.0 before assigning any value

### ISSUE THREAD

**Issue by pointyNeil** [rtklibexplorer/RTKLIB#78]
I had problems getting rnx2rtkp to produce any solutions. Adding debugging I narrowed-down the cause to the following line, where the test of P1==0.0 has undefined result as the variable wasn't assigned any value before. In my case it seemed to consistently equal 0.0 and cause prange() to return in error. Presumably with other compilers/systems the behaviour would be different. In my case it was on linux 4.9.0 amd64 with gcc 6.3.0.

https://github.com/rtklibexplorer/RTKLIB/blob/33570d4c0be1414025ac40796af170391f642ec3/src/pntpos.c#L89

Removing the P1==0.0 check it started working and I got sensible position solutions.

**Comment by rtklibexplorer** [comment]
Fixed in 1/18/21 commit.
