### ISSUE TITLE
RTKNAVI no fixed Through NTRIP centipede server

### ISSUE THREAD

**Issue by lucydjo** [rtklibexplorer/RTKLIB#92]
Hello, 

After spending 2 weeks on the subject, I can't get RTKNavie to work. That it is on Windows, Linux, Raspbery.
RTKNAVI remains quiet

![rtknavi screen](https://i.ibb.co/vwx0Tks/rtknavi-Jh6-BKXGQhj.png)

The NTRIP server works well and my hardware is not defective, I can get a position corrected in a few seconds using u-center. The problem comes from RTKNAVI.

My equipment : 
- Simplertk2b
- Raspberry pi 4 OR Windows 10 computer
- Documentation used : https://docs.centipede.fr/docs/Rover_rtklib_pc/RTKlib_windows.html
If anyone can tell me why RTKNAVI does not give me a corrected position, **thank you**.

**Comment by rtklibexplorer** [comment]
The lack of bars on the rover SNR plot indicates you are getting no valid rover observations.  You can the "Monitor" button or log the input to a file with the "L" button to debug this.
