### ISSUE TITLE
b34c cannot use SBAS

### ISSUE THREAD

**Issue by yandld** [rtklibexplorer/RTKLIB#93]
Hi,

I try B34C binary and found that SBAS cannot be used(using rtknvi.exe and 2 M8T, I confirm M8T SBAS is configured), after trace, I found obs. data is OK, but no eph. data.

**Comment by rtklibexplorer** [comment]
I just confirmed that I am receiving SBAS ephemeris data for WAAS SBAS satellites using a u-blox M8T with b34c RTKNAVI.  If you are still unable to make this work, please log the raw data and send it to me at rtklibexplorer@gmail.com

**Comment by yandld** [comment]
Thank you for the reply! I will have a double check on my local, thanks!
