### ISSUE TITLE
Command-line rtkpost.exe  (auto execute  btn on "winow show" and exit  btn on "done" message

### ISSUE THREAD

**Issue by ka9993** [rtklibexplorer/RTKLIB#94]
I use rtkpost.exe  most of the time within Python and batch file automated system in Win10.
However, rtkpost.exe is not command-line program but it read many of its parameters from its .INI .
So I modified rtkpost.exe (b34c) code to **auto-press the "execute button"** on the window show then **auto-press the "exit button"** on processing finish
I compiled my change and it is working fine
Please can you review this code and if OK , consider creating  **a new Command-line rtkpost.exe called cl-rtkpost.exe**  which will help people who need to integrate rtkpost.exe in their automated system.

Please check below 2 images and code
..
![111](https://user-images.githubusercontent.com/47154719/128776117-16635918-7a23-4b3e-86c4-25028d38e33b.png)
![333](https://user-images.githubusercontent.com/47154719/128776139-11017b24-6aac-4aa2-9fe4-d09ee0a756ce.png)
.
.
[RTKLIB-demo5.zip](https://github.com/rtklibexplorer/RTKLIB/files/6957515/RTKLIB-demo5.zip)

**Comment by rtklibexplorer** [comment]
Please use the RNX2RTKP post-processing CLI app for batch processing
