### ISSUE TITLE
Add the install file in the Cui compilation folder

### ISSUE THREAD

**Issue by asddaa452** [rtklibexplorer/RTKLIB#95]
# After running the make command in the consapp folder, the compiled executable files are scattered in various folders, so I wrote an install file so that they can be copied to the source file directory with one click.
### 
make
mkdir ../../RTKLIB_CUI_bin

cp convbin/gcc/convbin ../../RTKLIB_CUI_bin/convbin
cp pos2kml/gcc/pos2kml ../../RTKLIB_CUI_bin/pos2kml
cp rnx2rtkp/gcc/rnx2rtkp ../../RTKLIB_CUI_bin/rnx2rtkp
cp str2str/gcc/str2str ../../RTKLIB_CUI_bin/str2str

**Comment by rtklibexplorer** [comment]
I believe this is very similar to the install_consapp.bat file in the consapp folder.
